# Numpy

In [1]:
import numpy as np

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [3]:
arr = np.random.uniform(low = 0, high = 20, size = (4, 7))
arr

array([[ 6.6243572 ,  3.05082271,  0.22268095, 16.62698999, 19.48962673,
        11.58465645, 12.17639219],
       [ 6.85325638,  6.80560614,  8.63946656, 19.21942907,  6.46360889,
         4.3740066 , 16.2964849 ],
       [ 1.47946804, 13.49538657,  0.36618562,  7.72815129,  0.03707213,
        11.34125579,  2.13894697],
       [ 9.35947257, 16.97868587, 18.44363127,  0.22172671,  4.36932063,
         7.43988679,  8.93568695]])

In [5]:
(arr - arr.min())/(arr.max() - arr.min())

array([[0.33863342, 0.15492827, 0.00954162, 0.85284006, 1.        ,
        0.59362817, 0.6240476 ],
       [0.35040047, 0.34795091, 0.44222441, 0.98610991, 0.33036981,
        0.22294935, 0.83584974],
       [0.07414943, 0.69185332, 0.01691878, 0.3953763 , 0.        ,
        0.58111564, 0.10805135],
       [0.47923785, 0.87091974, 0.94622838, 0.00949256, 0.22270846,
        0.38055745, 0.45745225]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [7]:
arr = np.random.randint(low = 0, high = 11, size = (8, 10))
arr

array([[ 0,  3,  9,  3,  9,  8,  9,  5,  0,  9],
       [10,  5, 10,  6, 10,  2,  6,  9,  6,  0],
       [ 3,  1,  3,  3, 10, 10, 10,  1,  5,  1],
       [ 0,  9,  0, 10, 10,  4,  1,  9,  6,  6],
       [ 6, 10,  5,  4,  3, 10,  7,  5,  0,  5],
       [ 8,  3,  2,  5,  4,  1,  2,  8,  8,  2],
       [ 0,  5,  5,  3,  7,  1,  0,  8,  9, 10],
       [ 0,  6,  4,  1,  8,  5,  8,  2,  5,  8]])

In [9]:
sim_by_rows = arr.sum(axis = 1)
sim_by_rows

array([55, 64, 47, 55, 55, 43, 48, 47])

In [10]:
sim_by_rows.argmin()

5

In [12]:
arr[sim_by_rows.argmin(), :]

array([8, 3, 2, 5, 4, 1, 2, 8, 8, 2])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [14]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

In [16]:
X = np.linalg.inv(A) @ (-C) @ np.linalg.inv(B)
X

array([[ 1.00000000e+00,  1.02140518e-15],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

__При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.__

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [2]:
minutes_n_ingredients_arr = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32',
                                       skiprows = 1, delimiter = ',')

minutes_n_ingredients_arr[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [36]:
mean_minutes_n_ingredients_arr = np.mean(minutes_n_ingredients_arr[:,1:], axis = 0)
mean_minutes_n_ingredients_arr

array([2.16010017e+04, 9.05528000e+00])

In [33]:
min_minutes_n_ingredients_arr = np.min(minutes_n_ingredients_arr[:,1:], axis = 0)
min_minutes_n_ingredients_arr

array([0, 1], dtype=int32)

In [34]:
max_minutes_n_ingredients_arr = np.max(minutes_n_ingredients_arr[:,1:], axis = 0)
max_minutes_n_ingredients_arr

array([2147483647,         39], dtype=int32)

In [35]:
median_minutes_n_ingredients_arr = np.median(minutes_n_ingredients_arr[:,1:], axis = 0)
median_minutes_n_ingredients_arr

array([40.,  9.])

3. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [28]:
random_different_recipe = np.random.choice(len(minutes_n_ingredients_arr), 10, replace = False)
minutes_n_ingredients_arr[random_different_recipe]

array([[182492,     15,     10],
       [ 62632,      5,      8],
       [369282,     25,     11],
       [418635,     90,     10],
       [101618,     20,     10],
       [ 26983,     67,      8],
       [214874,     40,      8],
       [101195,     75,     10],
       [ 25502,    120,      9],
       [175797,   2165,      8]], dtype=int32)

4. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [30]:
minutes_n_ingredients_less_6 = np.where(minutes_n_ingredients_arr[:, 2] <= 5)[0]
len(minutes_n_ingredients_less_6)

17262

In [34]:
minutes_n_ingredients_less_6_ma = minutes_n_ingredients_arr[minutes_n_ingredients_less_6]
minutes_n_ingredients_less_6_ma

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

5. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [37]:
minutes_n_ingredients_less_mean = np.where(minutes_n_ingredients_arr[:, 2] < mean_minutes_n_ingredients_arr[1])[0]

len(minutes_n_ingredients_less_mean)/len(minutes_n_ingredients_arr) * 100

58.802

6. Вычислите значение $q_{0.75}$ третьего квартиля продолжительности выполнения рецепта. Замените в этом столбце значения, большие чем $q_{0.75}$ на величину $q_{0.75}$.

In [38]:
np.quantile(minutes_n_ingredients_arr[:, 1], 0.75)

65.0

In [59]:
minutes_n_ingredients_quantile_recipe = np.quantile(minutes_n_ingredients_arr[:, 1], 0.75)
np.where(minutes_n_ingredients_arr[:, 1] < np.quantile(minutes_n_ingredients_arr[:, 1], 0.75),
         minutes_n_ingredients_arr[:, 1],
        np.quantile(minutes_n_ingredients_arr[:, 1], 0.75))

array([60., 25., 10., ..., 65.,  5., 65.])

7. Посчитайте, для скольких рецептов исходного массива указана продолжительность, равная нулю. Модифицируйте исходный массив, заменив для таких строк значение в данном столбце на 1.

In [63]:
len(np.where(minutes_n_ingredients_arr[:,1] == 0)[0])

479

In [121]:
minutes_n_ingredients_arr[:,1] = np.where(minutes_n_ingredients_arr[:,1] == 0, 1, minutes_n_ingredients_arr[:,1])

8. Найдите множество возможных значений величины количества ингредиентов и количество вхождений каждого из уникальных значений в набор данных. Используя `numpy.isin`, выясните, какие числа из отрезка [1, 41] отсуствуют в данном множестве и выведите их на экран. 

In [83]:
np.unique(minutes_n_ingredients_arr[:,2], return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 37, 39], dtype=int32),
 array([   13,   926,  2895,  5515,  7913,  9376, 10628, 10951, 10585,
         9591,  8297,  6605,  4997,  3663,  2595,  1767,  1246,   790,
          573,   376,   217,   161,   105,    69,    50,    28,    16,
           16,    12,    12,     3,     1,     2,     1,     3,     1,
            1]))

In [106]:
mask = np.isin(np.arange(1,42), np.unique(minutes_n_ingredients_arr[:,2]))
np.arange(1,42)[np.logical_not(mask)]

array([36, 38, 40, 41])

9. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета.

In [125]:
mean_ingredients = minutes_n_ingredients_arr[:,2]/minutes_n_ingredients_arr[:,1]
mean_ingredients

array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
       0.1       ])

In [126]:
max(mean_ingredients)

24.0

10. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [212]:
minutes_n_ingredients_arr_top100 = np.copy(minutes_n_ingredients_arr)

minutes_n_ingredients_arr_top100 = minutes_n_ingredients_arr_top100[
    minutes_n_ingredients_arr_top100[:, 2].argsort()]
minutes_n_ingredients_arr_top100 = minutes_n_ingredients_arr_top100[::-1]
minutes_n_ingredients_arr_top100 = minutes_n_ingredients_arr_top100[:100]
np.mean(minutes_n_ingredients_arr_top100[:, 1])

227.87

11. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае. Выведите процент "простых" рецептов в датасете.

In [182]:
minutes_n_ingredients_arr_11 = np.where((minutes_n_ingredients_arr[:,1] <= 20)
                                        & (minutes_n_ingredients_arr[:,2] <= 5), 
                                        1, 0)
minutes_n_ingredients_arr_prost = np.copy(minutes_n_ingredients_arr)
minutes_n_ingredients_arr_prost = np.hstack((minutes_n_ingredients_arr_prost,
                                             minutes_n_ingredients_arr_11[:, np.newaxis]))
minutes_n_ingredients_arr_prost

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

In [186]:
sum(minutes_n_ingredients_arr_prost[:,3])/len(minutes_n_ingredients_arr_prost[:,3])

0.09552

12. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет не менее 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [25]:
minutes_n_ingredients_arr_duration_0 = np.where((minutes_n_ingredients_arr[:,1] < 10))[0]
minutes_n_ingredients_arr_duration_1 = np.where((minutes_n_ingredients_arr[:,1] < 20)
                                        & (minutes_n_ingredients_arr[:,1] >= 10))[0]
minutes_n_ingredients_arr_duration_2 = np.where(minutes_n_ingredients_arr[:,1] >= 20)[0]

min_minutes_n_ingredients = min(len(minutes_n_ingredients_arr_duration_0),
                                len(minutes_n_ingredients_arr_duration_1), 
                                len(minutes_n_ingredients_arr_duration_2))

minutes_n_ingredients_arr_duration_0 = minutes_n_ingredients_arr_duration_0[:min_minutes_n_ingredients]
minutes_n_ingredients_arr_duration_1 = minutes_n_ingredients_arr_duration_1[:min_minutes_n_ingredients]
minutes_n_ingredients_arr_duration_2 = minutes_n_ingredients_arr_duration_2[:min_minutes_n_ingredients]

np.array([minutes_n_ingredients_arr_duration_0, 
          minutes_n_ingredients_arr_duration_1, 
          minutes_n_ingredients_arr_duration_2])

array([[    3,     8,    13, ..., 99980, 99985, 99998],
       [    2,     6,     7, ..., 59871, 59874, 59883],
       [    0,     1,     4, ...,  9539,  9540,  9541]])

In [28]:
minutes_n_ingredients_arr_duration_0 = minutes_n_ingredients_arr[np.isin(minutes_n_ingredients_arr[:,1],
                                        np.where((minutes_n_ingredients_arr[:,1] < 10))[0])]
minutes_n_ingredients_arr_duration_1 = minutes_n_ingredients_arr[np.isin(minutes_n_ingredients_arr[:,1],
                                        np.where((minutes_n_ingredients_arr[:,1] < 20)
                                        & (minutes_n_ingredients_arr[:,1] >= 10))[0])]
minutes_n_ingredients_arr_duration_2 = minutes_n_ingredients_arr[np.isin(minutes_n_ingredients_arr[:,1],
                                        np.where(minutes_n_ingredients_arr[:,1] >= 20)[0])]

min_minutes_n_ingredients = min(len(minutes_n_ingredients_arr_duration_0),
                                len(minutes_n_ingredients_arr_duration_1),
                                len(minutes_n_ingredients_arr_duration_2))

minutes_n_ingredients_arr_duration_0 = minutes_n_ingredients_arr_duration_0[:min_minutes_n_ingredients]
minutes_n_ingredients_arr_duration_1 = minutes_n_ingredients_arr_duration_1[:min_minutes_n_ingredients]
minutes_n_ingredients_arr_duration_2 = minutes_n_ingredients_arr_duration_2[:min_minutes_n_ingredients]

np.array([minutes_n_ingredients_arr_duration_0,
          minutes_n_ingredients_arr_duration_1,
          minutes_n_ingredients_arr_duration_2])

array([[[446597,     15,      5],
        [328135,     15,      6],
        [ 95046,     15,      6],
        ...,
        [ 60756,     15,      5],
        [128811,     15,      4],
        [ 81993,    140,     14]],

       [[152828,     40,      7],
        [366174,      7,      9],
        [ 74205,     20,      7],
        ...,
        [436573,     40,      6],
        [315747,     20,      3],
        [ 28743,     40,     10]],

       [[127244,     60,     16],
        [ 23891,     25,      7],
        [ 94746,     10,      6],
        ...,
        [354944,     60,      9],
        [310051,     10,      8],
        [ 96737,     60,     16]]], dtype=int32)

13. Пусть в среднем одна минута работы повара стоит ресторану 5 ед., а средняя стоимость одного ингредиента составляет 10 ед. 
Создайте вектор-столбец `numpy`, содержащий данную информацию. Посчитайте среднюю стоимость приготовления для каждого из первых 10 рецептов в наборе данных.

In [203]:
minutes_n_ingredients_arr_money = np.copy(minutes_n_ingredients_arr)
minutes_n_ingredients_arr_money[:,1] = 5 * minutes_n_ingredients_arr_money[:,1]
minutes_n_ingredients_arr_money[:,2] = 10 * minutes_n_ingredients_arr_money[:,2]
np.mean(minutes_n_ingredients_arr_money[:10,1] + minutes_n_ingredients_arr_money[:10,2])

216.0

In [197]:
minutes_n_ingredients_arr_money

array([[127244,    300,    160],
       [ 23891,    125,     70],
       [ 94746,     50,     60],
       ...,
       [498432,    325,    150],
       [370915,     25,     40],
       [ 81993,    700,    140]], dtype=int32)